### ISSUE TITLE
Add support for Essentials v2 API

### ISSUE THREAD

**Issue by paladin0** [uptick/pymyob#38]
Is there a plan to expand this to the essentials/new essentials API?

**Comment by jarekwg** [comment]
Hi @paladin0,

Interesting. I've just had a quick read of the plan for essentials API. Looks like it's very compatible.

I believe all we'd need is a `product` flag to pass into the `Myob` constructor. For backwards compatibility, can default to `accountright`, but can be set to `essentials`. This will then dictate what base url is used.
The endpoints really do appear identical, which is pretty cool:
https://developer.myob.com/api/accountright/v2/contact/
https://developer.myob.com/api/accountright/essentials-new-v2/contact/
So I think we wouldn't need to bother with a separate endpoints file. Wherever there's missing feature parity, we'd leave it to MYOB's api to let the user know the endpoint is unavailable. If this turns out to be a bad idea, can always split them off in future.

So to answer your question, I think support for the new essentials can definitely be added to this package. Would you be interested in offering a PR to get us started?

Cheers,

**Comment by paladin0** [comment]
I think keeping them as the same is fine

however is this package already V2 compatible? as they have changed a few things
https://developer.myob.com/api/accountright/api-overview/v2-changes/

as i think there are more changes needed

**Comment by jarekwg** [comment]
Yep, this package _only_ support AccountRight Live v2
https://github.com/uptick/pymyob/blob/03fedacbd9034e58e6140f65f64478772f9693cd/myob/managers.py#L138

**Comment by jarekwg** [comment]
It appears the two have been merged entirely now. https://developer.myob.com/api/accountright/v2/
Probs safe to close this off.
