### ISSUE TITLE
Empty string returned from API causes JSON error

### ISSUE THREAD

**Issue by jpmoral-factory** [uptick/pymyob#55]
Version 1.2.4
Sending a DELETE request to the `Item/<uid>` endpoint returns an empty `200` response. This results in an error when the `Manager` tries to return JSON. (myob/managers.py line 92):

```
response.headers.get('content-type')
#=> application/json
response.json()
#=> *** simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
response.content
#=> b''
```

The problem is the API, since it specifies the content as `application/json` yet returns invalid JSON. But maybe the package can handle this somehow?

**Comment by jpmoral-factory** [comment]
It seems that whether `''` is valid JSON depends on who you ask:
https://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json

**Comment by jarekwg** [comment]
Ew -- happy to accept a PR that checks for this and sends off an automated email to MYOB to fix it.

But in seriousness, if you have time to make a PR that handles this gracefully (and signposts the added code with a little explanatory comment), I'll be happy to publish an update.

**Comment by jpmoral-factory** [comment]
@jarekwg hey, thanks for the response. A couple of follow-up questions:

1. Do you have a preferred approach? I was thinking either do a `try-except` for a JSON error or check if the content is an empty string.
2. Which do you think makes more sense here: an empty dict or `None`?
3. Given that we're on 1.2.4 and may not be able to upgrade, how do we do backports?

**Comment by jarekwg** [comment]
1. In this case, since we're expecting that emptystring to be coming through on deletes, let's catch that explicitly, and leave other errors to continue propagaing through:
```
try:
    return response.json()
except JSONDecodeError:
    # MYOB returns emptystring in this json responses to DELETE requests..
    if request_method == 'DELETE' and response.content = b'':
        return {}
    raise
```
2. Empty dict; caller is expecting a `dict` of some form, let's at least keep to that contract.
3. No backports. Each release is a tagged commit, not a whole branch. There have been no backwards-incompatible changes made since 1.2.4, other than maybe some trouble installing from eggs (#52), so you should be fine to just bump your version.

**Comment by jpmoral-factory** [comment]
@jarekwg right, thanks.

**Comment by jpmoral-factory** [comment]
Stuff came up, I'll see if I can get to this next week.
